# Project information
site_name: Devops Automation
site_url: https://sameeralam3127.github.io/Devops-automation/
site_author: Sameer Alam
docs_dir: docs

# Copyright1
copyright: Copyright &copy; 2016 - 2025 Sameer Alam

theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: simple/suse
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: simple/suse
      danger: simple/redhat
      bug: fontawesome/solid/robot
      example: simple/ubuntu
      quote: fontawesome/solid/quote-left

  features:
    - navigation.instant # Single page instant refresh
    - navigation.tabs # Navigation tabs across top
    - navigation.tracking # URL updated with active anchor
    - navigation.sections # Top-level tabs rendered in sidebar
    - navigation.top # Back to top button at bottom right
    - navigation.expand # Expand left sidebar by default
    #- navigation.tabs.sticky # Tab always displayed
    - navigation.indexes
    - search.suggest
    - search.share
    - search.highlight
    - toc.integrate # Integrate page TOC in left sidebar - wider page
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips
    - content.tooltips
    - navigation.search # Search bar in navigation
    - navigation.subsections # Show subsections in navigation
    - content.social.share # Social sharing buttons

  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables
  - def_list
  - md_in_html
  - abbr

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:

nav:
  - Home: index.md
  - Docker:
      - Containerization techniques: docker/docker.md
  - Kubernetes:
      - Kubernetes clusters: kubernetes/kubernetes.md
  - Jenkins:
      - Automating CI/CD pipelines with Jenkins: jenkins/jenkins.md
  - SonarQube: sonarqube/sonarqube.md
  - Monitoring Tools:
      - Grafana: monitoring-tools/log.md
  - Shell Scripts: shell-scripts/scripts.md
  - Ansible: ansible/ansible.md

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
