# Project information
site_name: Compute Central
site_url: https://www.computecentral.in/
site_author: Sameer Alam
# Copyright
copyright: Copyright &copy; 2016 - 2025 Sameer Alam

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    #- navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono


# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
 


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 0
  


# Page tree
nav:
  - Home: index.md
  - Docker:
      - Containerization techniques: docker/docker.md
  - Kubernetes:
      - Managing containerized applications in Kubernetes clusters: kubernetes/kubernetes.md    
  - Jenkins:
      - Automating CI/CD pipelines with Jenkins: jenkins/jenkins.md
  - SonarQube:
      - Implementing continuous inspection of code quality: sonarqube/code-quality.md
  - CI/CD Tools:
      - Full CI/CD pipeline examples: cicd-tools/pipeline-examples.md
  - Shell Scripts:
      - Handy scripts to automate routine tasks: shell-scripts/handy-scripts.md
  - Ansible:
      - Automating infrastructure management and provisioning: ansible/ansible.md

extra:
  generator: false

extra_css:
  - stylesheets/extra.css