# Project information
site_name: Compute Central
site_url: https://www.computecentral.in/
site_author: Sameer Alam
docs_dir: docs

# Copyright
copyright: Copyright &copy; 2016 - 2025 Sameer Alam

theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: simple/suse
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: simple/suse
      danger: simple/redhat
      bug: fontawesome/solid/robot
      example: simple/ubuntu
      quote: fontawesome/solid/quote-left 
 
  features:
      - navigation.instant # Single page instant refresh
      - navigation.tabs # Navigation tabs across top
      - navigation.tracking # URL updated with active anchor
      - navigation.sections # Top-level tabs rendered in sidebar
      - navigation.top # Back to top button at bottom right
      - navigation.expand # Expand left sidebar by default
      - navigation.tabs.sticky # Tab always displayed
      - navigation.indexes
      - search.suggest
      - search.share
      - search.highlight
      - toc.integrate # Integrate page TOC in left sidebar - wider page
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
      - content.code.select
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.footnote.tooltips
      - content.tooltips

  language: en

  
  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
 
  - md_in_html
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search

nav:
  - Home: index.md
  - Docker:
      - Containerization techniques: docker/docker.md
  - Kubernetes:
      - Kubernetes clusters: kubernetes/kubernetes.md    
  - Jenkins:
      - Automating CI/CD pipelines with Jenkins: jenkins/jenkins.md
  - SonarQube:
      - Implementing continuous inspection of code quality: sonarqube/sonarqube.md
  - Monitoring Tools:
      - Full CI/CD pipeline examples: cicd-tools/pipeline-examples.md
  - Shell Scripts:
      - Handy scripts to automate routine tasks: shell-scripts/handy-scripts.md
  - Ansible:
      - Automating infrastructure management and provisioning: ansible/ansible.md

extra:
  generator: false

extra_css:
  - stylesheets/extra.css